# basic options
title: Your awesome title
author: UTA HKN
email: your-email@domain.com
description: A wonderful site meant to help mentor EE students
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
